// eslint-disable-next-line import/no-anonymous-default-export
export const messageTypes = {
  GAME_ADDED: "GAME_ADDED",
  GAME_START: "GAME_START",
  PARTICIPANT_JOINED: "PARTICIPANT_JOINED",
  GAME_FULL: "GAME_FULL",
  ROUND_START: "ROUND_START",
  DEAL_CARDS: "DEAL_CARDS",
  CURRENT_PLAYER: "CURRENT_PLAYER",
  CARD_PLAYER: "CARD_PLAYER",
  ROUND_END: "ROUND_END",
  SCORE_UPDATED: "SCORE_UPDATED",
  GAME_END: "GAME_END",
};
