const cards = [
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank2",
    rankValue: 2,
    rankNumber: 2,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank3",
    rankValue: 3,
    rankNumber: 3,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank4",
    rankValue: 4,
    rankNumber: 4,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank5",
    rankValue: 5,
    rankNumber: 5,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank6",
    rankValue: 6,
    rankNumber: 6,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank7",
    rankValue: 7,
    rankNumber: 7,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank8",
    rankValue: 8,
    rankNumber: 8,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank9",
    rankValue: 9,
    rankNumber: 9,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank10",
    rankValue: 10,
    rankNumber: 10,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank11",
    rankValue: "J",
    rankNumber: 11,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank12",
    rankValue: "Q",
    rankNumber: 12,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank13",
    rankValue: "K",
    rankNumber: 13,
  },
  {
    suit: 1,
    suitName: "hearts",
    rank: "rank1",
    rankValue: "A",
    rankNumber: 1,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank2",
    rankValue: 2,
    rankNumber: 2,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank3",
    rankValue: 3,
    rankNumber: 3,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank4",
    rankValue: 4,
    rankNumber: 4,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank5",
    rankValue: 5,
    rankNumber: 5,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank6",
    rankValue: 6,
    rankNumber: 6,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank7",
    rankValue: 7,
    rankNumber: 7,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank8",
    rankValue: 8,
    rankNumber: 8,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank9",
    rankValue: 9,
    rankNumber: 9,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank10",
    rankValue: 10,
    rankNumber: 10,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank11",
    rankValue: "J",
    rankNumber: 11,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank12",
    rankValue: "Q",
    rankNumber: 12,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank13",
    rankValue: "K",
    rankNumber: 13,
  },
  {
    suitName: "diamonds",
    suit: 2,
    rank: "rank1",
    rankValue: "A",
    rankNumber: 1,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank2",
    rankValue: 2,
    rankNumber: 2,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank3",
    rankValue: 3,
    rankNumber: 3,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank4",
    rankValue: 4,
    rankNumber: 4,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank5",
    rankValue: 5,
    rankNumber: 5,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank6",
    rankValue: 6,
    rankNumber: 6,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank7",
    rankValue: 7,
    rankNumber: 7,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank8",
    rankValue: 8,
    rankNumber: 8,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank9",
    rankValue: 9,
    rankNumber: 9,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank10",
    rankValue: 10,
    rankNumber: 10,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank11",
    rankValue: "J",
    rankNumber: 11,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank12",
    rankValue: "Q",
    rankNumber: 12,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank13",
    rankValue: "K",
    rankNumber: 13,
  },
  {
    suit: 3,
    suitName: "clubs",
    rank: "rank1",
    rankValue: "A",
    rankNumber: 1,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank2",
    rankValue: 2,
    rankNumber: 2,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank3",
    rankValue: 3,
    rankNumber: 3,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank4",
    rankValue: 4,
    rankNumber: 4,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank5",
    rankValue: 5,
    rankNumber: 5,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank6",
    rankValue: 6,
    rankNumber: 6,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank7",
    rankValue: 7,
    rankNumber: 7,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank8",
    rankValue: 8,
    rankNumber: 8,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank9",
    rankValue: 9,
    rankNumber: 9,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank10",
    rankValue: 10,
    rankNumber: 10,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank11",
    rankValue: "J",
    rankNumber: 11,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank12",
    rankValue: "Q",
    rankNumber: 12,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank13",
    rankValue: "K",
    rankNumber: 13,
  },
  {
    suit: 0,
    suitName: "spades",
    rank: "rank1",
    rankValue: "A",
    rankNumber: 1,
  },
];

const game = {
  amountOfParticipants: 0,
  participants: [],
  hasStarted: false,
  mode: "1-8-1",
  currentRound: 0,
  scores: {},
};

const profile = {
  name: "Example data",
  email: "example@mail.com",
};

module.exports = {
  cards,
  profile,
  game,
};
