export const cardsActionTypes = {
  LOAD_CARDS_SUCCESS: "LOAD_CARDS_SUCCESS",
  LOAD_DECK_SUCCESS: "LOAD_DECK_SUCCESS",
};

export const gameActionTypes = {
  LOAD_GAME_SUCCESS: "LOAD_GAME_SUCCESS",
  UPDATE_GAME_SUCCESS: "UPDATE_GAME_SUCCESS",
  SET_DECK_SUCCESS: "SET_DECK_SUCCESS",
  SET_PARTICIPANTS_SUCCESS: "SET_PARTICIPANTS_SUCCESS",
  SET_HAND_SUCCESS: "SET_HAND_SUCCESS",
  SET_SCORES_SUCCESS: "SET_SCORES_SUCCESS",
};
